name: dev_ci

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Gcloud login
        run: gcloud auth configure-docker

      - name: Build Docker Image and Push
        run: |
          docker build -t asia.gcr.io/angelic-shift-296514/stockml:v0 -f docker/app/Dockerfile ..
          docker push asia.gcr.io/angelic-shift-296514/stockml:v0
        env:
          WINDSCRIBE_USR: ${{ secrets.WINDSCRIBE_USR }}
          WINDSCRIBE_PASS: ${{ secrets.WINDSCRIBE_PASS }}
          
      - name: Create gcloud instance with container
        run: gcloud compute instances create-with-container stockml-1 --container-image asia.gcr.io/angelic-shift-296514/stockml:v0 --zone asia-east1-a
  
